trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: terraform-secrets   # This must be created in Azure DevOps Library
- name: TF_IN_AUTOMATION
  value: 'true'
- name: TF_DIR
  value: 'Azure-VM-Ubunutu'

steps:
- checkout: self

- task: PowerShell@2
  displayName: 'Terraform Init'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_DIR)
      terraform init

- task: PowerShell@2
  displayName: 'Terraform Import (One-Time)'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_DIR)
      terraform state list | findstr azurerm_resource_group.rg > $null
      if (!$?) {
        Write-Host "Resource not in state. Importing..."
        terraform import azurerm_resource_group.rg /subscriptions/$(ARM_SUBSCRIPTION_ID)/resourceGroups/Ram-linux-vm-rg
      } else {
        Write-Host "Resource already exists in state. Skipping import."
      }

- task: PowerShell@2
  displayName: 'Terraform Plan'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_DIR)
      terraform plan -out=tfplan

- task: PowerShell@2
  displayName: 'Terraform Apply'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_DIR)
      terraform apply -auto-approve tfplan
